apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "alertmanager-tg.labels" . | nindent 4 }}
  name: {{ include "alertmanager-tg.fullname" . }}
type: Opaque
data:
  token: {{ .Values.bot.telegramToken | b64enc | quote }}
